version: '3'

services:
  web:
    build: api
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn server.wsgi --preload --log-file - -b 0.0.0.0:8000"
    env_file:
      - api/.env
    ports:
      - "8000:8000"