version: '3'

services:
  web:
    build: api
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn server.wsgi --preload --log-file - -b 0.0.0.0:8000"
    env_file:
      - api/.env
    ports:
      - "8000:8000"

  client:
    build: client
    ports:
      - 3000:3000
    volumes:
      - ./client/pages:/app/pages
      - ./client/public:/app/public
      - ./client/styles:/app/styles
      - ./client/components:/app/components