# Generated by Django 4.2.1 on 2023-05-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
